# Generated by Django 3.0.7 on 2020-10-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Quass',
            new_name='Quaas',
        ),
    ]
