# Generated by Django 3.0.7 on 2020-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_remove_squirrel_approaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
